# -*- coding: utf-8 -*-

"""This file was auto-generated by PyFlow exporter
    'Python exporter v1.0.0'
    Created: 01:42PM on September 05, 2025
"""

EXPORTER_NAME = 'Python exporter'
EXPORTER_VERSION = '1.0.0'


# ======================== VARIABLES AND PARAMETERS SETUP =========================
VARS = {}


# ================================ PACKAGE IMPORTS ================================
# pylint: disable=wrong-import-position
from sqlalchemy import (create_engine,
                        URL)
# pylint: enable=wrong-import-position

# ================================= PACKAGE SETUPS ================================


# ================================ SYSTEM FUNCTIONS ===============================
def connect_sqlserver(db_host, db_name, trusted_conn):
    """Connect to an SQL server according to the parameters"""
    engine = create_engine(
        URL.create('mssql+pyodbc', query={'odbc_connect':
            f"Driver=SQL Server;Server={db_host};" + \
            f"Database={db_name};" + \
            f"Trusted_Connection={'yes' if trusted_conn else 'no'};"}
        ),
        fast_executemany=False,
        use_setinputsizes=False
    )
    return engine



# ============================== GRAPH IMPLEMENTATION =============================


# ================================== MAIN PROGRAM =================================


# ------- SQLServerConn_inExec -------
SQLServerConn_out = connect_sqlserver('aaa', 'bbb', True)
