# -*- coding: utf-8 -*-

"""This file was auto-generated by PyFlow exporter
    'Python exporter v1.0.0'
    Created: 09:04AM on October 02, 2025
"""

EXPORTER_NAME = 'Python exporter'
EXPORTER_VERSION = '1.0.0'


# ======================== VARIABLES AND PARAMETERS SETUP =========================
VARS = {}


# ================================ PACKAGE IMPORTS ================================
# pylint: disable=wrong-import-position
import xlwings as xw
import pandas as pd
# pylint: enable=wrong-import-position

# ================================= PACKAGE SETUPS ================================


# ================================ SYSTEM FUNCTIONS ===============================
def openExcel(path):
    """Open an Excel file with xlwings"""
    return xw.Book(path, update_links=False)


def loadExcelTable(book, table_name):
    """Reads an Excel Table object and returns the data as a Pandas DataFrame"""
    if book is not None:
        for ws in book.sheets:
            for t in ws.tables:
                if t.name==table_name:
                    data = t.range.options(pd.DataFrame, index=False).value
                    return data
    return None


def closeExcel(book):
    """Close an xlwings workbook"""
    if book is not None:
        book.close()




# ============================== GRAPH IMPLEMENTATION =============================


# ================================== MAIN PROGRAM =================================


# ------- OpenExcel_inExec -------
OpenExcel_out = openExcel('tests\\graphs\\test_data.xlsx')
LoadExcelTable_out = loadExcelTable(OpenExcel_out, 'tData1')
closeExcel(OpenExcel_out)
print(LoadExcelTable_out)
